site_name: vTeam Documentation
site_description: AI-powered automation system for engineering refinement
site_author: Red Hat AI Engineering Team
site_url: https://vteam-docs.example.com

repo_name: ambient-code/vTeam
repo_url: https://github.com/ambient-code/vTeam
edit_uri: edit/main/docs/

# Exclude files from the documentation build
exclude_docs: |
  README.md

theme:
  name: material
  palette:
    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: red  
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.annotate

nav:
  - Home: index.md
  - User Guide:
    - Overview: user-guide/index.md
    - Getting Started: user-guide/getting-started.md
  - Labs:
    - Overview: labs/index.md
    - Lab 1 - Your First Agentic Session: labs/basic/lab-1-first-rfe.md
  - Reference:
    - Overview: reference/index.md
    - Glossary: reference/glossary.md
  - Deployment Guides:
    - GitHub App Setup: GITHUB_APP_SETUP.md
    - OpenShift Deployment: OPENSHIFT_DEPLOY.md
    - OpenShift OAuth: OPENSHIFT_OAUTH.md
    - Claude Code Runner: CLAUDE_CODE_RUNNER.md

plugins:
  - search
  - mermaid2

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - toc:
      permalink: true