---
# ServiceAccount for deployments in ambient-code namespace
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployer
  namespace: ambient-code
---
# Secret to generate a long-lived token for the service account
apiVersion: v1
kind: Secret
metadata:
  name: deployer-token
  namespace: ambient-code
  annotations:
    kubernetes.io/service-account.name: deployer
type: kubernetes.io/service-account-token
---
# ClusterRole with minimal deployment permissions based on components/manifests
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ambient-code-deployer-role
rules:
  # Core resources
  - apiGroups: [""]
    resources:
      - namespaces
      - services
      - serviceaccounts
      - secrets
      - configmaps
      - persistentvolumeclaims
      - pods
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Additional core resources needed for RBAC grant permissions
  - apiGroups: [""]
    resources:
      - serviceaccounts/token
      - pods/log
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Apps
  - apiGroups: ["apps"]
    resources:
      - deployments
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Batch jobs
  - apiGroups: ["batch"]
    resources:
      - jobs
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # RBAC - needs full access to manage ClusterRoles
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - clusterroles
      - clusterrolebindings
      - rolebindings
      - roles
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Custom Resource Definitions
  - apiGroups: ["apiextensions.k8s.io"]
    resources:
      - customresourcedefinitions
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # vTeam Custom Resources
  - apiGroups: ["vteam.ambient-code"]
    resources:
      - agenticsessions
      - projectsettings
      - rfeworkflows
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # vTeam Custom Resources status
  - apiGroups: ["vteam.ambient-code"]
    resources:
      - agenticsessions/status
      - projectsettings/status
      - rfeworkflows/status
    verbs: ["get", "update", "patch"]

  # OpenShift Routes
  - apiGroups: ["route.openshift.io"]
    resources:
      - routes
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # OpenShift Projects
  - apiGroups: ["project.openshift.io"]
    resources:
      - projects
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Authentication (for TokenReview)
  - apiGroups: ["authentication.k8s.io"]
    resources:
      - tokenreviews
    verbs: ["create"]
---
# ClusterRoleBinding to bind the ClusterRole to the service account for cluster-scoped resources
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ambient-code-deployer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ambient-code-deployer-role
subjects:
  - kind: ServiceAccount
    name: deployer
    namespace: ambient-code
