apiVersion: apps/v1
kind: Deployment
metadata:
  name: vteam-backend
  labels:
    app: vteam-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vteam-backend
  template:
    metadata:
      labels:
        app: vteam-backend
    spec:
      serviceAccountName: backend-api
      initContainers:
      - name: init-workspace
        image: registry.access.redhat.com/ubi9/ubi-minimal:9.5
        command: ['sh', '-c', 'mkdir -p /workspace/sessions && chmod 755 /workspace/sessions']
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: backend-state
          mountPath: /workspace
      containers:
      - name: backend
        image: image-registry.openshift-image-registry.svc:5000/vteam-dev/vteam-backend:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PORT
          value: "8080"
        - name: STATE_BASE_DIR
          value: "/workspace"
        - name: AGENTS_DIR
          value: "/app/agents"
        # Spec-kit configuration for RFE seeding
        - name: SPEC_KIT_REPO
          value: "ambient-code/spec-kit-rh"
        - name: SPEC_KIT_VERSION
          value: "main"
        - name: SPEC_KIT_TEMPLATE
          value: "spec-kit-template-claude-sh"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: backend-state
          mountPath: /workspace
      volumes:
      - name: backend-state
        persistentVolumeClaim:
          claimName: backend-state-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: vteam-backend
  labels:
    app: vteam-backend
spec:
  selector:
    app: vteam-backend
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: vteam-backend
  labels:
    app: vteam-backend
spec:
  to:
    kind: Service
    name: vteam-backend
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
