apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-state-pvc
  labels:
    app: backend-api
    component: state-storage
spec:
  accessModes:
    - ReadWriteOnce  # single backend replica mounted to RWO PVC
  # Note: storageClassName must be specified for CRC as it has no default storage class
  storageClassName: crc-csi-hostpath-provisioner
  resources:
    requests:
      storage: 5Gi
