apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ambient-namespace-viewer
rules:
# OpenShift Projects: Read-only cluster-wide list
# OpenShift API server automatically filters to show only accessible projects
- apiGroups: ["project.openshift.io"]
  resources: ["projects"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ambient-users-can-list-projects
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ambient-namespace-viewer
subjects:
# Grant to all authenticated users
# Note: On vanilla k8s, backend will verify access per-namespace instead of relying on this
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated

