apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backend-api
rules:
# AgenticSessions (backend is sole writer)
- apiGroups: ["vteam.ambient-code"]
  resources: ["agenticsessions"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["vteam.ambient-code"]
  resources: ["agenticsessions/status"]
  verbs: ["get", "update", "patch"]

# ServiceAccounts (create per-session SA; also patch access-key SAs for last-used)
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get", "list", "create", "update", "patch"]

# TokenRequests for SA JWT mint (per-session runner; access keys)
- apiGroups: [""]
  resources: ["serviceaccounts/token"]
  verbs: ["create"]
# ConfigMaps for GitHub installation mapping
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "create", "update", "patch"]

# TokenReviews for runner SA validation
- apiGroups: ["authentication.k8s.io"]
  resources: ["tokenreviews"]
  verbs: ["create"]

# RBAC objects for per-session Role/RoleBinding
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]

# Secrets to store per-session BOT_TOKEN
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
# ConfigMaps for GitHub installation mapping
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "create", "update", "patch"]

# RFEWorkflow custom resources (full CRUD + status updates)
- apiGroups: ["vteam.ambient-code"]
  resources: ["rfeworkflows"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["vteam.ambient-code"]
  resources: ["rfeworkflows/status"]
  verbs: ["get", "update", "patch"]


