apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ambient-frontend-auth
rules:
- apiGroups: ["authentication.k8s.io"]
  resources: ["tokenreviews"]
  verbs: ["create"]
- apiGroups: ["authorization.k8s.io"]
  resources: ["subjectaccessreviews"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ambient-frontend-auth
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ambient-frontend-auth
subjects:
- kind: ServiceAccount
  name: frontend
