name: AI Assessment Comment Labeler

on:
  issues:
    types: [labeled]

permissions:
  issues: write
  models: read
  contents: read

jobs:
  ai-assessment:
    runs-on: ubuntu-latest
    if: contains(github.event.label.name, 'ai-review') || contains(github.event.label.name, 'request ai review')

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
      - name: Run AI assessment
        uses: github/ai-assessment-comment-labeler@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_number: ${{ github.event.issue.number }}
          issue_body: ${{ github.event.issue.body }}
          ai_review_label: 'ai-review'
          prompts_directory: './Prompts'
          labels_to_prompts_mapping: 'bug,bug-assessment.prompt.yml|enhancement,feature-assessment.prompt.yml|question,general-assessment.prompt.yml|documentation,general-assessment.prompt.yml|default,general-assessment.prompt.yml'