name: Deploy Documentation to Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: registry.access.redhat.com/ubi9/ubi-minimal:latest
    steps:
      - name: Install git
        run: |
          microdnf install -y git

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python and dependencies
        run: |
          microdnf install -y python3.11 python3.11-pip
          python3.11 -m pip install --upgrade pip
          python3.11 -m pip install -r requirements-docs.txt

      - name: Build documentation
        run: |
          python3.11 -m mkdocs build --strict

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
